server:
    port: 8081

spring:
    h2:
        console:
        enabled: true
        path: /h2-console
    datasource:
        url: jdbc:h2:mem:weatherdb
        driverClassName: org.h2.Driver
        username: weather
        password: weather
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
    sql:
        init:
            mode: always
